In [1]:
import numpy as np

In [37]:
poly = np.array([[0], [1], [2]])
X = np.array([3, 6, 9])
Y = np.array([1, 2, 3])

print(X)
print(poly)
print(X ** poly[1])
X_poly = np.ones((X.shape[0], 1))
print(X_poly)
print((X ** poly[0]).reshape(1, -1))
print(np.vstack((X_poly, X @ poly[0])))
for i in range(1, len(poly)):
  X_poly = np.vstack((X_poly, X ** poly[i]))

X_poly

[3 6 9]
[[0]
 [1]
 [2]]
[3 6 9]
[[1.]
 [1.]
 [1.]]
[[1 1 1]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)