# 1

In [160]:
import numpy as np

Stwórz tablice 2 wymiarową 4 elementową. Sprawdź wymiar i kształt
macierzy.

In [161]:
tablica_2d = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11], [13, 14, 15]])
tablica_2d.shape, tablica_2d.ndim

((4, 3), 2)

Zmień kształt tablicy na tablicę 2 i 6 elementową.

In [162]:
tablica_2d.reshape(2, -1)

array([[ 1,  2,  3,  5,  6,  7],
       [ 9, 10, 11, 13, 14, 15]])

In [163]:
tablica_2d.reshape(6, -1)

array([[ 1,  2],
       [ 3,  5],
       [ 6,  7],
       [ 9, 10],
       [11, 13],
       [14, 15]])

Stwórz tablicę zawiera ciąg arytmetyczny o zadanym przyroście.

In [164]:
ciag_arytmetyczny = np.arange(0, 20, 2)
ciag_arytmetyczny

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Stwórz tablicę zawiera ciąg arytmetyczny złożony z wartości z przedziału [a,b].

In [165]:
a, b = 5, 25
ciag_przedział = np.linspace(a, b, 10)
ciag_przedział

array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
       16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ])

Stwórz macierz: jednostkową, wypełnioną zerami i jedynkami.

Jednostkowa:

In [166]:
macierz_jednostkowa = np.eye(4)
macierz_jednostkowa

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Zera:

In [167]:
macierz_zera = np.zeros((4, 4))
macierz_zera

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Jedynki:

In [168]:
macierz_jedynki = np.ones((4, 4))
macierz_jedynki

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Stwórz macierz 4x2, a następnie dodaj do niej dowolny element.

In [169]:
macierz_4x2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
macierz_4x2_rozszerzona = np.append(macierz_4x2, [[9, 10]], axis=0)
macierz_4x2_rozszerzona

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Stwórz 2 różne macierze, a następnie wykonaj na nich operacje: +, -, *, /, **, //,
%.

In [170]:
macierz_A = np.array([[2, 3], [4, 5], [6, 7]])
macierz_B = np.array([[1, 2], [3, 4], [5, 6]])

dodawanie = macierz_A + macierz_B
odejmowanie = macierz_A - macierz_B
mnozenie = macierz_A * macierz_B
dzielenie = macierz_A / macierz_B
potegowanie = macierz_A ** 2
dzielenie_całkowite = macierz_A // macierz_B
reszta = macierz_A % macierz_B

print("Dodawanie:")
print(dodawanie)
print("\nOdejmowanie:")
print(odejmowanie)
print("\nMnożenie (element-wise):")
print(mnozenie)
print("\nDzielenie:")
print(dzielenie)
print("\nPotęgowanie:")
print(potegowanie)
print("\nDzielenie całkowite:")
print(dzielenie_całkowite)
print("\nReszta z dzielenia:")
print(reszta)

Dodawanie:
[[ 3  5]
 [ 7  9]
 [11 13]]

Odejmowanie:
[[1 1]
 [1 1]
 [1 1]]

Mnożenie (element-wise):
[[ 2  6]
 [12 20]
 [30 42]]

Dzielenie:
[[2.         1.5       ]
 [1.33333333 1.25      ]
 [1.2        1.16666667]]

Potęgowanie:
[[ 4  9]
 [16 25]
 [36 49]]

Dzielenie całkowite:
[[2 1]
 [1 1]
 [1 1]]

Reszta z dzielenia:
[[0 1]
 [1 1]
 [1 1]]


# 2

Stwórz macierz o 150 wierszach i 4 kolumach:

In [171]:
import seaborn as sns
import numpy as np
iris = np.array(sns.load_dataset("iris").iloc[:,0:4])

iris.shape

(150, 4)

Dokonaj standaryzacji wszystkich zmiennych, tj. w każdej kolumnie od każdej
obserwacji odejmij wartość średniej arytmetycznej i podziel ja przez
odchylenie standardowe.

In [172]:
srednia = np.mean(iris, axis=0)
odchylenie = np.std(iris, axis=0)

iris_standaryzowana = (iris - srednia) / odchylenie

np.std(iris_standaryzowana, axis=0), np.mean(iris_standaryzowana, axis=0)


(array([1., 1., 1., 1.]),
 array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16]))

Zaimplementuj algorytm sortowania szybkiego, wykorzystując funkcję/metodę
partition().

In [173]:
import random


vector = np.random.randint(-100, 500, 100)

def quicksort(arr: np.ndarray) -> np.ndarray:
    arr_len = len(arr)
    if arr_len <= 1:
        return arr

    pivot = random.randint(0, arr_len - 1)

    partitioned = np.partition(arr, pivot)

    return np.concat((quicksort(partitioned[:pivot]), [partitioned[pivot]],  quicksort(partitioned[pivot+1:]))) 

print("Before")
print(vector)
print("After")
sorted_vector = quicksort(vector)
print(sorted_vector)
print("Is sorted?")
print(np.array_equal(sorted_vector, np.sort(vector)))

Before
[221 484 478 243 -58 271 288 100 469  51 -64 -77 425 454 330 323 108 123
  -7 136 -42   2 -38 -23 251  27 235 104 364 -87 403 294 323 302  -8 399
 -48 413  91   4  59  19 -40 175  72 -84  76 -95 460 -55 409 -30 478 -24
  79  27 -40 314 362 434 486 161 187 425 -22 341   5 303 -99  17 369 325
 277 365 443  14 252 154 161 374 306 270 425  10 288  60 447 114  41  41
 456 441 349 -30 250 -80 235 119 333 -77]
After
[-99 -95 -87 -84 -80 -77 -77 -64 -58 -55 -48 -42 -40 -40 -38 -30 -30 -24
 -23 -22  -8  -7   2   4   5  10  14  17  19  27  27  41  41  51  59  60
  72  76  79  91 100 104 108 114 119 123 136 154 161 161 175 187 221 235
 235 243 250 251 252 270 271 277 288 288 294 302 303 306 314 323 323 325
 330 333 341 349 362 364 365 369 374 399 403 409 413 425 425 425 434 441
 443 447 454 456 460 469 478 478 484 486]
Is sorted?
True


Napisz funkcję, która wywołując unique() (z odpowiednimi argumentami),
wyznacza modę (dominantę) wartości w podanym wektorze.

In [174]:
vector = np.random.randint(0, 2, 10)

def find_dominant(arr: np.ndarray):
  elements, counts = np.unique(arr, return_counts=True)
  max_count = np.max(counts)

  return elements[np.where(counts == max_count)]

print(vector)
find_dominant(vector)


[1 0 0 1 1 1 1 1 0 0]


array([1])

# 3

In [175]:
import numpy as np
import pandas as pd
import seaborn as sns

flights = sns.load_dataset("flights")
tips = sns.load_dataset("tips")
iris = sns.load_dataset("iris")

Sprawdź rozmiar ramki danych flights, tips, iris. Wywołaj metody head(), tail()
oraz info() na obiektach flights, tips, iris.

In [176]:
flights.head(), flights.tail(), flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   year        144 non-null    int64   
 1   month       144 non-null    category
 2   passengers  144 non-null    int64   
dtypes: category(1), int64(2)
memory usage: 2.9 KB


(   year month  passengers
 0  1949   Jan         112
 1  1949   Feb         118
 2  1949   Mar         132
 3  1949   Apr         129
 4  1949   May         121,
      year month  passengers
 139  1960   Aug         606
 140  1960   Sep         508
 141  1960   Oct         461
 142  1960   Nov         390
 143  1960   Dec         432,
 None)

In [177]:
tips.head(), tips.tail(), tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


(   total_bill   tip     sex smoker  day    time  size
 0       16.99  1.01  Female     No  Sun  Dinner     2
 1       10.34  1.66    Male     No  Sun  Dinner     3
 2       21.01  3.50    Male     No  Sun  Dinner     3
 3       23.68  3.31    Male     No  Sun  Dinner     2
 4       24.59  3.61  Female     No  Sun  Dinner     4,
      total_bill   tip     sex smoker   day    time  size
 239       29.03  5.92    Male     No   Sat  Dinner     3
 240       27.18  2.00  Female    Yes   Sat  Dinner     2
 241       22.67  2.00    Male    Yes   Sat  Dinner     2
 242       17.82  1.75    Male     No   Sat  Dinner     2
 243       18.78  3.00  Female     No  Thur  Dinner     2,
 None)

In [178]:
iris.head(), iris.tail(), iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


(   sepal_length  sepal_width  petal_length  petal_width species
 0           5.1          3.5           1.4          0.2  setosa
 1           4.9          3.0           1.4          0.2  setosa
 2           4.7          3.2           1.3          0.2  setosa
 3           4.6          3.1           1.5          0.2  setosa
 4           5.0          3.6           1.4          0.2  setosa,
      sepal_length  sepal_width  petal_length  petal_width    species
 145           6.7          3.0           5.2          2.3  virginica
 146           6.3          2.5           5.0          1.9  virginica
 147           6.5          3.0           5.2          2.0  virginica
 148           6.2          3.4           5.4          2.3  virginica
 149           5.9          3.0           5.1          1.8  virginica,
 None)

Ramka danych flights zawiera kolumny year i month. Wygneruj na ich
podstawie nową zmienną typu data i czas.

In [179]:
def month_to_num(name: str) -> int:
  month_mapping = {
    "Jan": 1,
    "Feb": 2,
    "Mar": 3,
    "Apr": 4,
    "May": 5,
    "Jun": 6,
    "Jul": 7,
    "Aug": 8,
    "Sep": 9,
    "Oct": 10,
    "Nov": 11,
    "Dec": 12
  }
  return month_mapping.get(name, 0)

new_flights = flights.copy()
new_flights["datetime"] = pd.to_datetime(
  new_flights["year"].astype(str) + "-" + 
  new_flights["month"].apply(month_to_num).astype(str) + "-01"
)

new_flights

year month  passengers   datetime
0    1949   Jan         112 1949-01-01
1    1949   Feb         118 1949-02-01
2    1949   Mar         132 1949-03-01
3    1949   Apr         129 1949-04-01
4    1949   May         121 1949-05-01
..    ...   ...         ...        ...
139  1960   Aug         606 1960-08-01
140  1960   Sep         508 1960-09-01
141  1960   Oct         461 1960-10-01
142  1960   Nov         390 1960-11-01
143  1960   Dec         432 1960-12-01

[144 rows x 4 columns]

Zastosuj wektor etykiet hierarchicznych do nazwania wierszy ramki danych
flights. Wykorzystaj do tego celu dane zawarte w kolumnie year i month.

In [180]:
flights_indexed = flights.set_index(['year', 'month'])
flights_indexed

passengers
year month            
1949 Jan           112
     Feb           118
     Mar           132
     Apr           129
     May           121
...                ...
1960 Aug           606
     Sep           508
     Oct           461
     Nov           390
     Dec           432

[144 rows x 1 columns]

Podziel ramkę danych irys na dwie rozłączne części: pierwsza 80%
obserwacji, druga 20%.

In [181]:
whole_len = len(iris)
train_len = int(0.8 * whole_len)

eighty_iris = iris[:train_len]
twenty_iris = iris[train_len:]

eighty_iris.shape, twenty_iris.shape

((120, 5), (30, 5))

Dokonaj standaryzacji wszystkich zmiennych liczbowych w ramce danych iris.

In [182]:
iris_numeric = iris.select_dtypes(include=[np.number])

srednia = np.mean(iris_numeric, axis=0)
odchylenie = np.std(iris_numeric, axis=0)

iris_standardized_numeric = (iris_numeric - srednia) / odchylenie

iris[iris_numeric.columns] = iris_standardized_numeric

np.std(iris_standardized_numeric, axis=0), np.mean(iris_standardized_numeric, axis=0), iris.head()


(sepal_length    1.0
 sepal_width     1.0
 petal_length    1.0
 petal_width     1.0
 dtype: float64,
 sepal_length   -4.736952e-16
 sepal_width    -7.815970e-16
 petal_length   -4.263256e-16
 petal_width    -4.736952e-16
 dtype: float64,
    sepal_length  sepal_width  petal_length  petal_width species
 0     -0.900681     1.019004     -1.340227    -1.315444  setosa
 1     -1.143017    -0.131979     -1.340227    -1.315444  setosa
 2     -1.385353     0.328414     -1.397064    -1.315444  setosa
 3     -1.506521     0.098217     -1.283389    -1.315444  setosa
 4     -1.021849     1.249201     -1.340227    -1.315444  setosa)

Wyznacz podstawowe statystyki próbkowe (średnia, odchylenie standardowe,
kwartyle) dla liczby pasażerów (flights) w każdym roku z sobna. Przedstaw
wyniki w taki sposób, by zagregowane wartości przechowywane były
w kolumnach, a kolejne lata w wierszach.

In [187]:
flights.groupby('year')['passengers'].agg([
    ('średnia', 'mean'),
    ('odchylenie_standardowe', 'std'),
    ('Q1', lambda x: x.quantile(0.25)),
    ('mediana', 'median'),
    ('Q3', lambda x: x.quantile(0.75))
])

średnia  odchylenie_standardowe      Q1  mediana      Q3
year                                                             
1949  126.666667               13.720147  118.00    125.0  135.25
1950  139.666667               19.070841  125.75    137.5  151.25
1951  170.166667               18.438267  159.00    169.0  179.50
1952  197.000000               22.966379  180.75    192.0  211.25
1953  225.000000               28.466887  199.75    232.0  238.50
1954  238.916667               34.924486  221.25    231.5  260.25
1955  284.000000               42.140458  260.75    272.0  312.75
1956  328.250000               47.861780  300.50    315.0  359.75
1957  368.416667               57.890898  330.75    351.5  408.50
1958  381.000000               64.530472  339.25    360.5  411.75
1959  428.333333               69.830097  387.50    406.5  465.25
1960  476.166667               77.737125  418.50    461.0  514.75